fullnameOverride: secret-sync-source

controller:
  syncMode: source
  sourceNamespace: secret-sync-vcluster
  logVerbose: true
  bridgeAllowedSubjects: system:serviceaccount:secret-sync-vcluster-system:secret-sync-controller

service:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: secret-sync-source.example.test
      paths:
        - path: /
          pathType: Prefix
